### ISSUE TITLE
Using String values as keyPath fails when using getById

### ISSUE THREAD

**Issue by pklitscher** [harshzalavadiya/use-indexeddb#222]
Great work, thank you for this repo, loving it.

Just came across an issue where using String values as the id does not work. 

You can write to the database with a String value such as `"abc"` fine. However when you do a `getById` it fails

String values as a number as opposed to other characters appears to have different behaviour. 

To explain better I made a small demo

https://codesandbox.io/s/competent-hill-5w9v5

Cheers

**Comment by harshzalavadiya** [comment]
@pklitscher new release should fix this bug
